### ISSUE TITLE
jmeter 压力测试时的错误 对象池已释放，无法访问

### ISSUE THREAD

**Issue by the404** [ctstone/csredis#55]
System.ObjectDisposedException: Cannot access a disposed object.
Object name: '【192.168.3.13:6379/0】对象池已释放，无法访问。'.
at SafeObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
at SafeObjectPool.ObjectPool`1.GetAsync()
at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump)
at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)

**Comment by JesseXia** [comment]
You'd better not speak Chinese, otherwise nobody can answer you.

**Comment by willtoto** [comment]
我也碰到了这个问题 网上也找不到相关的解决方案
